services:
  moss-tts-nano:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moss-tts-nano
    ports:
      - "18083:18083"
    volumes:
      - ./models:/app/models
      - ./generated_audio:/app/generated_audio
      - ./hf-cache:/app/.cache/huggingface
    environment:
      HF_HOME: /app/.cache/huggingface
    restart: unless-stopped
